[package]
name = "sdk_gen"
version = "0.1.0"
authors = ["rkr35 <rkr35@dragons.drexel.edu>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["gen_sdk"]
gen_sdk = []

[dependencies]
common = { path = "../common" }
macros = { path = "../macros" }
